# Ingress Controller
# Updated timeout, needed for installing the nginx controller
update_settings ( max_parallel_updates = 3 , k8s_upsert_timeout_secs = 60 , suppress_unused_image_warnings = None )

load('ext://helm_resource', 'helm_resource', 'helm_repo')
helm_repo('ingress-nginx-repo', 'https://kubernetes.github.io/ingress-nginx')
helm_resource('ingress-nginx', 'ingress-nginx/ingress-nginx',
    resource_deps=['ingress-nginx-repo']
)
k8s_resource(workload='ingress-nginx', port_forwards='9002:80')