load('.infra/k8s/nginx/Tiltfile')

# Dependency Track
helm_repo('evryfs-oss', 'https://evryfs.github.io/helm-charts/', labels=['dependency-track'])

k8s_yaml('./namespace.yaml')
k8s_resource(new_name='dependency-track-namespace', objects=['dependency-track:namespace'], labels=['dependency-track'])

helm_resource('dependency-track', 'evryfs-oss/dependency-track',
    resource_deps=['evryfs-oss', 'dependency-track-namespace'],
    namespace='dependency-track',
    labels=['dependency-track'],
    flags=[
      '--values=./deptrack.values.yaml',
    ],
    deps=[
        './deptrack.values.yaml'
    ]
)